version: '3'

services:
  homeassistant:
    container_name: ha-omlet-test
    image: ghcr.io/home-assistant/home-assistant:stable
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=America/New_York
    volumes:
      - ./config:/config
      - ./custom_components/omlet:/config/custom_components/omlet
    ports:
      - "8123:8123"
    network_mode: host 